name: 'Test - Android SDK Repository and Use Case test report action'
description: 'test report'
author: 'AmityCo'

branding:
  icon: 'git-pull-request'
  color: 'green'

runs:
  using: 'docker'
  image: 'Dockerfile'
